package main

import (
	"github.com/imroc/req"
	"log"
	"encoding/json"
)

type AutoGenerated []struct {
	Naam      string `json:"naam"`
	ImgURLSec string `json:"img_url_sec"`
	Prijs     string `json:"prijs"`
	ImgURL    string `json:"img_url"`
}

func main() {
		r, _ := req.Get("https://raw.githubusercontent.com/oliverwk/wttpknng/master/Lingerie.json")
		log.Fatalln(r)

		var users AutoGenerated

		// we unmarshal our byteArray which contains our
		// jsonFile's content into 'users' which we defined above
		json.Unmarshal(r, &users)

		// we iterate through every user within our users array and
		// print out the user Type, their name, and their facebook url
		// as just an example
		for i := 0; i < len(users.AutoGenerated); i++ {
			  log.Fatalln("User Type: " + users.AutoGenerated.naam)
		   log.Fatalln("User Type: " + users.AutoGenerated[i].naam)
		   log.Fatalln("User Name: " + users.AutoGenerated[i].prijs)
		   log.Fatalln("Facebook Url: " + users.AutoGenerated[i].ImgURL)
		}




}
